### ISSUE TITLE
Create the directory structure

### ISSUE THREAD

**Issue by WBRK-dev** [DaioEnma/enma.rs#1]
Create the directory structure.
This includes documentation like so:

```
root
- extractors _(This is where we get the sources)_
- parsers _(This is where we extract and format the page data)_
- etc...
```

**Comment by ritesshg** [comment]
> Create the directory structure. This includes documentation like so:
> 
> ```
> root
> - extractors _(This is where we get the sources)_
> - parsers _(This is where we extract and format the page data)_
> - etc...
> ```

Hey @WBRK-dev, I've thought of the structure below, what do you think?
```sh
src
├── anime
│   ├── extractors
│   │   └── megacloud.rs
│   ├── hianime
│   │   ├── parsers
│   │   │   ├── home_page.rs
│   │   │   └── etc...
│   │   ├── error.rs
│   │   └── mod.rs
│   ├── anicrush
│   └── etc...
├── manga
│   └── (same structure as anime)
├── anime.rs
├── manga.rs
└── lib.rs
```
